# Generated by Django 5.0.3 on 2024-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vegetables', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vegetable',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='vegetable',
            name='proximity',
        ),
    ]
