# Generated by Django 5.0.3 on 2024-03-12 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
        ('months', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='fruits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fruits.fruit'),
        ),
    ]
