# Generated by Django 5.0.3 on 2024-03-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0001_initial'),
        ('months', '0002_month_fruits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='fruits',
        ),
        migrations.AddField(
            model_name='month',
            name='fruits',
            field=models.ManyToManyField(to='fruits.fruit'),
        ),
    ]
