# Generated by Django 5.0.3 on 2024-03-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('months', '0003_remove_month_fruits_month_fruits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='fruits',
        ),
    ]
