# Generated by Django 5.0.3 on 2024-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fruits', '0002_alter_fruit_blocked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fruit',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='fruit',
            name='proximity',
        ),
    ]
